version: '3.8'

services:
  pressure-measurement-app.api:
    build:
      context: PressureMeasurementApp.API/
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5000:5000"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  pressure-measurement-app.client:
    build:
      context: client-app/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://pressure-measurement-app.api:5000
    depends_on:
      pressure-measurement-app.api:
        condition: service_started
    networks:
      - app-network

networks:
  app-network:
    driver: bridge