version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: pressure-redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  pressure-measurement-app.api:
    build:
      context: PressureMeasurementApp.API/
      dockerfile: Dockerfile
    container_name: pressure-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__Redis=redis:6379
    ports:
      - "5000:5000"
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

  pressure-measurement-app.client:
    build:
      context: client-app/
      dockerfile: Dockerfile
    container_name: pressure-client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://pressure-measurement-app.api:5000
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge